name: Build Daydream API (1.21)

on:
  push:
    branches: [ ver/1.21.8 ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Configure Git User Details
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "Github Actions"

      - name : Build and Publish API with Gradle
        run: |
          echo "::group::Apply Patches"
          ./gradlew applyPaperSingleFilePatches applyPaperApiPatches --stacktrace
          echo "::endgroup::"
          echo "::group::Build API"
          ./gradlew build
          echo "::endgroup::"
          echo "::group::Generate Javadoc"
          ./gradlew javadoc
          echo "::endgroup::"
          echo "::group::Publish API to Maven Repository"
          ./gradlew publishAllPublicationsToMavenRepository
          echo "::endgroup::"
        env:
          DEPLOY_ID: ${{ secrets.DEPLOY_ID }}
          DEPLOY_PW: ${{ secrets.DEPLOY_PW }}
