name: Build Daydream API (1.19)

on:
  push:
    branches: [ ver/1.19.4 ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: 'gradle'

      - name: Setup git config
        run: |
         git config --global user.email "no-reply@github.com"
         git config --global user.name "Github Action"

      - name : Build with Gradle
        run: |
         ./gradlew applyApiPatches --no-daemon
         ./gradlew build --no-daemon

      - name: Publish package
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publishAllPublicationsToMavenRepository
        env:
          DEPLOY_ID: ${{ secrets.DEPLOY_ID }}
          DEPLOY_PW: ${{ secrets.DEPLOY_PW }}
